---
- name: install r1soft agent
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: create repo
      when: ansible_os_family == "Redhat"
      copy:
        src: r1soft.repo
        dest: /etc/yum.repos.d
      ignore_errors: true


    - name: create repo for Ubuntu
      when: ansible_os_family == "Debian"
      shell: "{{ item }}"
      with_items:
        - "apt-get install wget -y"
        - "echo deb http://repo.r1soft.com/apt stable main >> /etc/apt/sources.list"
        - "wget http://repo.r1soft.com/r1soft.asc"
        - "apt-key add r1soft.asc"
        - "apt-get update"
        - "apt-get install serverbackup-enterprise-agent"


    - name: install
      package:
        name: serverbackup-enterprise-agent
        state: installed
      ignore_errors: true
 

     
    - name: start agent
      systemd:
        name: sbm-agent
        state: restarted
      ignore_errors: true


    - name: stop firewall
      systemd:
        name: firewalld
        state: stopped        
      ignore_errors: tru

    - name: Get key
      shell: "r1soft-setup --get-key  http://34.242.57.49:8080/
"
